import { StyleSheet } from 'react-native';

export const s = StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: '#0D0D12',
  },
  scroll: {
    flex: 1,
    paddingHorizontal: 24,
    paddingTop: 60,
  },
  content: {
    paddingBottom: 24,
  },
  title: {
    color: '#FFFFFF',
    fontSize: 32,
    fontWeight: '700',
    marginBottom: 8,
    letterSpacing: -0.5,
  },
  subtitle: {
    color: '#6B7280',
    fontSize: 15,
    marginBottom: 28,
    fontWeight: '400',
  },

  inputContainer: {
    backgroundColor: '#16161D',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#2A2A35',
    paddingHorizontal: 16,
    paddingVertical: 4,
  },
  input: {
    color: '#FFFFFF',
    fontSize: 15,
    paddingVertical: 14,
    fontWeight: '400',
  },

  btnRow: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 16,
  },
  btn: {
    flex: 1,
    backgroundColor: '#14F195',
    paddingVertical: 16,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#14F195',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 8,
  },
  btnDisabled: {
    opacity: 0.6,
  },
  btnText: {
    color: '#0D0D12',
    fontWeight: '600',
    fontSize: 16,
    letterSpacing: 0.3,
  },
  btnGhost: {
    paddingVertical: 16,
    paddingHorizontal: 20,
    borderRadius: 14,
    backgroundColor: '#16161D',
    borderWidth: 1,
    borderColor: '#2A2A35',
  },
  btnGhostText: {
    color: '#9CA3AF',
    fontSize: 15,
    fontWeight: '500',
  },

  card: {
    backgroundColor: '#16161D',
    borderRadius: 24,
    padding: 28,
    alignItems: 'center',
    marginTop: 28,
    borderWidth: 1,
    borderColor: '#2A2A35',
  },
  label: {
    color: '#6B7280',
    fontSize: 13,
    fontWeight: '500',
    textTransform: 'uppercase',
    letterSpacing: 1.2,
  },
  balanceRow: {
    flexDirection: 'row',
    alignItems: 'baseline',
    marginTop: 8,
  },
  balance: {
    color: '#FFFFFF',
    fontSize: 48,
    fontWeight: '700',
    letterSpacing: -1,
  },
  sol: {
    color: '#14F195',
    fontSize: 18,
    fontWeight: '600',
    marginLeft: 8,
  },
  addr: {
    color: '#9945FF',
    fontSize: 13,
    fontFamily: 'monospace',
    marginTop: 16,
    backgroundColor: '#1E1E28',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
    overflow: 'hidden',
  },

  section: {
    color: '#FFFFFF',
    fontSize: 20,
    fontWeight: '600',
    marginTop: 32,
    marginBottom: 16,
    letterSpacing: -0.3,
  },

  row: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#16161D',
    paddingVertical: 16,
    paddingHorizontal: 18,
    borderRadius: 14,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: '#2A2A35',
  },
  mint: {
    color: '#FFFFFF',
    fontSize: 14,
    fontFamily: 'monospace',
    fontWeight: '500',
  },
  amount: {
    color: '#14F195',
    fontSize: 15,
    fontWeight: '600',
  },
  time: {
    color: '#6B7280',
    fontSize: 12,
    marginTop: 4,
    fontWeight: '400',
  },
  statusIcon: {
    fontSize: 18,
    fontWeight: '600',
  },
  tabBar: {
    flexDirection: 'row',
    backgroundColor: '#16161D',
    borderTopWidth: 1,
    borderTopColor: '#2A2A35',
    paddingBottom: 8,
    paddingTop: 12,
  },
  tab: {
    flex: 1,
    alignItems: 'center',
    gap: 4,
  },
  tabLabel: {
    color: '#6B7280',
    fontSize: 12,
  },
  tabActive: {
    color: '#14F195',
  },
  arrowContainer: {
    alignItems: 'center',
    marginVertical: -22,
    zIndex: 10,
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  tokenSelector: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#252530',
    paddingLeft: 8,
    paddingRight: 12,
    paddingVertical: 8,
    borderRadius: 24,
    gap: 6,
  },
  tokenIcon: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  tokenIconText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  tokenName: {
    fontSize: 18,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  amountInput: {
    fontSize: 40,
    fontWeight: '400',
    color: '#FFFFFF',
    textAlign: 'right',
    flex: 1,
    marginLeft: 10,
  },
  cardFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 12,
  },
  balanceText: {
    fontSize: 14,
    color: '#666666',
  },
  usdText: {
    fontSize: 14,
    color: '#666666',
  },
  swapArrow: {
    backgroundColor: '#0D0D12',
    width: 44,
    height: 44,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 3,
    borderColor: '#0D0D12',
  },
  swapBtn: {
    backgroundColor: '#14F195',
    paddingVertical: 18,
    borderRadius: 16,
    alignItems: 'center',
    marginTop: 24,
  },
  swapBtnText: {
    color: '#000000',
    fontSize: 18,
    fontWeight: '600',
  },
  container: {
    flex: 1,
    backgroundColor: '#0a0a1a',
    paddingTop: 60,
    paddingHorizontal: 16,
  },
  center: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#0a0a1a',
  },
  backButton: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 20,
  },
  backText: {
    color: '#fff',
    fontSize: 16,
    marginLeft: 8,
  },
  header: {
    marginBottom: 20,
  },
  cardLabel: {
    color: '#888',
    fontSize: 12,
    textTransform: 'uppercase',
    letterSpacing: 1,
    marginBottom: 8,
  },
  mintAddress: {
    color: '#9945FF',
    fontSize: 13,
    fontFamily: 'monospace',
  },
  infoRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 8,
  },
  infoLabel: {
    color: '#888',
    fontSize: 14,
  },
  infoValue: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '600',
  },
  divider: {
    height: 1,
    backgroundColor: '#2a2a3e',
  },
  linkButton: {
    backgroundColor: '#9945FF20',
    padding: 14,
    borderRadius: 10,
    alignItems: 'center',
    marginTop: 8,
  },
  linkButtonText: {
    color: '#9945FF',
    fontSize: 14,
    fontWeight: '600',
  },
});
